name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md' # ignore changes to readmes
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    uses: li0ard/workflow/.github/workflows/test.yml@14b353c12e0b7d50b8942c3c0b68918624dfa205